files:
  - source: /core/src/main/res/values/strings.xml
    translation: /core/src/main/res/values-%two_letters_code%/strings.xml
  - source: /base/src/main/res/values/strings.xml
    translation: /base/src/main/res/values-%two_letters_code%/strings.xml
