name: Build
on: [pull_request, push]

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare secure.properties
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> base/secure.properties
          echo "SENTRY_DNS=${{ secrets.SENTRY_DNS }}" >> base/secure.properties
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
          java-package: jdk
      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare secure.properties
        run: |
          echo "MAPS_API_KEY=${{ secrets.MAPS_API_KEY }}" >> base/secure.properties
          echo "SENTRY_DNS=${{ secrets.SENTRY_DNS }}" >> base/secure.properties
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: app
          path: base/build/outputs/apk/debug/EscalarAlcoiaIComtat-debug.apk