name: Release Drafter

on: [push, pull_request]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare Gradle secure file
        run: |
          echo 'ext {' >> base/secure.gradle
          echo 'MAPBOX_DOWNLOADS_TOKEN="${{ secrets.MAPBOX_TOKEN_SECRET }}"' >> base/secure.gradle
          echo 'MAPBOX_PUBLIC_TOKEN="${{ secrets.MAPBOX_TOKEN_PUBLIC }}"' >> base/secure.gradle
          echo 'SENTRY_DNS="${{ secrets.SENTRY_DNS }}"' >> base/secure.gradle
          echo 'SIGNING_KEYSTORE_PASSWORD="${{ secrets.SIGNING_KEYSTORE_PASSWORD }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_ALIAS="${{ secrets.SIGNING_KEY_ALIAS }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_PASSWORD="${{ secrets.SIGNING_KEY_PASSWORD }}"' >> base/secure.gradle
          echo '}' >> base/secure.gradle
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Prepare Gradle version file
        run: |
          echo "ext {" >> base/version.gradle
          echo "VERSION_NAME=\"${{ steps.create_release.outputs.tag_name }}\"" >> base/version.gradle
          echo "}" >> base/version.gradle

      - name: Run tests
        id: test
        run: bash ./gradlew test --stacktrace

      - name: Build APK
        id: build_apk
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew assembleRelease --stacktrace
      - name: APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK Artifact
          path: ./base/build/outputs/apk/release/EscalarAlcoiaIComtat-release.apk
