name: Docs Generator

on: push

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0

      - name: Prepare secure files 🔒
        run: |
          echo 'ext {' >> base/secure.gradle
          echo 'MAPBOX_DOWNLOADS_TOKEN="${{ secrets.MAPBOX_TOKEN_SECRET }}"' >> base/secure.gradle
          echo 'MAPBOX_PUBLIC_TOKEN="${{ secrets.MAPBOX_TOKEN_PUBLIC }}"' >> base/secure.gradle
          echo 'SENTRY_DNS="${{ secrets.SENTRY_DNS }}"' >> base/secure.gradle
          echo 'SIGNING_KEYSTORE_PASSWORD="${{ secrets.SIGNING_KEYSTORE_PASSWORD }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_ALIAS="${{ secrets.SIGNING_KEY_ALIAS }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_PASSWORD="${{ secrets.SIGNING_KEY_PASSWORD }}"' >> base/secure.gradle
          echo 'PARSE_SERVER="${{ secrets.PARSE_SERVER }}"' >> base/secure.gradle
          echo 'PARSE_KEY="${{ secrets.PARSE_KEY }}"' >> base/secure.gradle
          echo 'PARSE_APPLICATION_ID="${{ secrets.PARSE_APPLICATION_ID }}"' >> base/secure.gradle
          echo '}' >> base/secure.gradle

          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties

          echo "ext {" >> base/version.gradle
          echo "VERSION_NAME=\"${{ steps.create_release.outputs.tag_name }}\"" >> base/version.gradle
          echo "}" >> base/version.gradle
      - name: Run dokka 📝
        id: test
        run: bash ./gradlew dokka
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs