name: Docs Generator

on: push

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 🛎️
        uses: actions/checkout@v2
        with:
          submodules: false
          fetch-depth: 0
      - name: Run dokka 📝
        id: test
        run: bash ./gradlew dokka
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: /