name: Release Drafter

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches to consider in the event; optional, defaults to all
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk
      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare Gradle secure file
        run: |
          echo "ext {" >> base/secure.gradle
          echo "MAPS_API_KEY=\"${{ secrets.MAPS_API_KEY }}\"" >> base/secure.gradle
          echo "SENTRY_DNS=\"${{ secrets.SENTRY_DNS }}\"" >> base/secure.gradle
          echo "SIGNING_KEYSTORE_PASSWORD=\"${{ secrets.SIGNING_KEYSTORE_PASSWORD }}\"" >> base/secure.gradle
          echo "SIGNING_KEY_ALIAS=\"${{ secrets.SIGNING_KEY_ALIAS }}\"" >> base/secure.gradle
          echo "SIGNING_KEY_PASSWORD=\"${{ secrets.SIGNING_KEY_PASSWORD }}\"" >> base/secure.gradle
          echo "}" >> base/secure.gradle
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Build debug APK
        id: build_apk
        run: bash ./gradlew assembleRelease --stacktrace
      - uses: release-drafter/release-drafter@v5
        id: create_release
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./base/build/outputs/apk/release/EscalarAlcoiaIComtat*.apk
          asset_name: EscalarAlcoiaIComtat.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORGANIZATION }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ steps.create_release.outputs.tag_name }}
