name: Release Drafter

on:
  push:
    branches:
      - master

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Create release
        uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk

      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare Gradle secure file
        run: |
          echo 'ext {' >> base/secure.gradle
          echo 'MAPBOX_DOWNLOADS_TOKEN="${{ secrets.MAPBOX_TOKEN_SECRET }}"' >> base/secure.gradle
          echo 'MAPBOX_PUBLIC_TOKEN="${{ secrets.MAPBOX_TOKEN_PUBLIC }}"' >> base/secure.gradle
          echo 'SENTRY_DNS="${{ secrets.SENTRY_DNS }}"' >> base/secure.gradle
          echo 'SIGNING_KEYSTORE_PASSWORD="${{ secrets.SIGNING_KEYSTORE_PASSWORD }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_ALIAS="${{ secrets.SIGNING_KEY_ALIAS }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_PASSWORD="${{ secrets.SIGNING_KEY_PASSWORD }}"' >> base/secure.gradle
          echo 'PARSE_SERVER="${{ secrets.PARSE_SERVER }}"' >> base/secure.gradle
          echo 'PARSE_KEY="${{ secrets.PARSE_KEY }}"' >> base/secure.gradle
          echo 'PARSE_APPLICATION_ID="${{ secrets.PARSE_APPLICATION_ID }}"' >> base/secure.gradle
          echo '}' >> base/secure.gradle
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Prepare Gradle version file
        run: |
          truncate -s 0 base/version.gradle
          echo "ext {" >> base/version.gradle
          echo "VERSION_NAME=\"${{ steps.create_release.outputs.tag_name }}\"" >> base/version.gradle
          echo "}" >> base/version.gradle
          cat base/version.gradle

      - name: Build APK
        id: build_apk
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew assembleRelease --stacktrace
      - name: APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK Artifact
          path: ./base/build/outputs/apk/release/EscalarAlcoiaIComtat-release.apk

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":robot: Commit Changes"
          file_pattern: "gradle.properties base/version.gradle"

      - name: Build AAB
        id: build_aab
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew :base:bundleRelease --stacktrace
      - name: AAB Artifact
        id: aab_artifact
        uses: actions/upload-artifact@v2
        with:
          name: AAB Artifact
          path: ./base/build/outputs/bundle/release/EscalarAlcoiaIComtat-release.aab

      - name: Prepare changelog
        id: prepare_changelog
        run: |
          mkdir -p -- "./changelog"
          echo "${{ steps.create_release.outputs.body }}" > ./changelog/whatsnew-en-US
          # Remove all the markdown title double hashtag (##)
          sed -i 's/## //g' ./changelog/whatsnew-en-US
          # Remove the "Changes" title.
          sed -i 's/Changes//g' ./changelog/whatsnew-en-US
          # Remove markdown emojis
          sed -i 's/:.*: //g' ./changelog/whatsnew-en-US
          # Insert a line jump
          echo >> ./changelog/whatsnew-en-US
          # Insert the "more info url"
          echo "More info at: ${{ steps.create_release.outputs.html_url }}" >> ./changelog/whatsnew-en-US
          cat ./changelog/whatsnew-en-US

      - name: Upload to Play Store
        id: upload_play_store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.arnyminerz.escalaralcoiaicomtat
          releaseFiles: ./base/build/outputs/bundle/release/EscalarAlcoiaIComtat-release.aab
          track: internal
          inAppUpdatePriority: 2
#          mappingFile: ./base/build/outputs/mapping/release/mapping.txt
          whatsNewDirectory: ./changelog
