name: Release Drafter

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
    # branches to consider in the event; optional, defaults to all
    branches:
      - master
      - dev

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Draft release
        uses: release-drafter/release-drafter@v5
        id: create_release
        with:
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: '15'
          java-package: jdk

      - name: Prepare google-services.json
        run: echo "${{ secrets.GOOGLE_SERVICES }}" >> base/google-services.json
      - name: Prepare Gradle secure file
        run: |
          echo 'ext {' >> base/secure.gradle
          echo 'MAPS_API_KEY="${{ secrets.MAPS_API_KEY }}"' >> base/secure.gradle
          echo 'MAPBOX_DOWNLOADS_TOKEN="${{ secrets.MAPBOX_TOKEN_SECRET }}"' >> base/secure.gradle
          echo 'MAPBOX_PUBLIC_TOKEN="${{ secrets.MAPBOX_TOKEN_PUBLIC }}"' >> base/secure.gradle
          echo 'SENTRY_DNS="${{ secrets.SENTRY_DNS }}"' >> base/secure.gradle
          echo 'SIGNING_KEYSTORE_PASSWORD="${{ secrets.SIGNING_KEYSTORE_PASSWORD }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_ALIAS="${{ secrets.SIGNING_KEY_ALIAS }}"' >> base/secure.gradle
          echo 'SIGNING_KEY_PASSWORD="${{ secrets.SIGNING_KEY_PASSWORD }}"' >> base/secure.gradle
          echo '}' >> base/secure.gradle
      - name: Prepare sentry.properties
        run: |
          echo "defaults.project=${{ secrets.SENTRY_PROJECT }}" >> sentry.properties
          echo "defaults.org=${{ secrets.SENTRY_ORGANIZATION }}" >> sentry.properties
          echo "auth.token=${{ secrets.SENTRY_TOKEN }}" >> sentry.properties
      - name: Prepare Gradle version file
        run: |
          echo "ext {" >> base/version.gradle
          echo "VERSION_NAME=\"${{ steps.create_release.outputs.tag_name }}\"" >> base/version.gradle
          echo "}" >> base/version.gradle

      - name: Build APK
        id: build_apk
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew assembleRelease --stacktrace
      - name: APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: APK Artifact
          path: ./base/build/outputs/apk/release/EscalarAlcoiaIComtat-release.apk

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ":robot: Commit Changes"
          file_pattern: "gradle.properties"

      - name: Create Sentry release
        uses: getsentry/action-release@v1
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORGANIZATION }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        with:
          environment: production
          version: ${{ steps.create_release.outputs.tag_name }}

      - name: Build AAB
        id: build_aab
        run: |
          echo "Building ${{ steps.create_release.outputs.tag_name }}..."
          bash ./gradlew :base:bundleRelease --stacktrace
      - name: AAB Artifact
        uses: actions/upload-artifact@v2
        with:
          name: AAB Artifact
          path: ./base/build/outputs/bundle/release/EscalarAlcoiaIComtat-release.aab

      - name: Upload APK file
        id: upload_apk_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./base/build/outputs/apk/release/EscalarAlcoiaIComtat-release.apk
          asset_name: EscalarAlcoiaIComtat.apk
          asset_content_type: application/vnd.android.package-archive
      - name: Upload AAB
        id: upload_aab_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./base/build/outputs/bundle/release/EscalarAlcoiaIComtat-release.aab
          asset_name: EscalarAlcoiaIComtat.aab
          asset_content_type: application/octet-stream

      - name: Debug Symbols Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Debug Symbols Artifact
          path: ./base/build/outputs/native-debug-symbols/release/native-debug-symbols.zip
      - name: Upload Symbols file
        id: upload_symbols_asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./base/build/outputs/native-debug-symbols/release/native-debug-symbols.zip
          asset_name: native-debug-symbols.zip
          asset_content_type: application/zip
